name: cardvault
description: "A secure card and bank account management app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  u_credit_card: ^1.3.1
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  shared_preferences: ^2.3.2
  flutter_animate: ^4.5.0
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  cloud_functions:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  image_path: "Assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "Assets/images/logo.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - Assets/images/
    - Assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: Assets/fonts/Roboto-Bold.ttf
        - asset: Assets/fonts/Roboto-Medium.ttf
        - asset: Assets/fonts/Roboto-Regular.ttf