// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGmysj5yPPc95EaEBJoDgkmNsmCDLkUEw',
    appId: '1:319535347690:android:0f05dc6eafffb95acfa493',
    messagingSenderId: '319535347690',
    projectId: 'card-vault-6d7f8',
    storageBucket: 'card-vault-6d7f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo9S_s45ypJ4YE4s9jzLce2LZ4IfoOtkY',
    appId: '1:319535347690:ios:589958109901d4f3cfa493',
    messagingSenderId: '319535347690',
    projectId: 'card-vault-6d7f8',
    storageBucket: 'card-vault-6d7f8.appspot.com',
    androidClientId: '319535347690-k1lclpqmdk60jak0ji7em1ufgof95pcb.apps.googleusercontent.com',
    iosClientId: '319535347690-au550dv3g4q3off38lbj0k42ulao9o4r.apps.googleusercontent.com',
    iosBundleId: 'com.apsify.cardvault',
  );

}